// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuranSchool.Api.Data;

#nullable disable

namespace QuranSchool.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815170608_AddBackupDirectorySupport")]
    partial class AddBackupDirectorySupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuranSchool.Api.Models.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_academic_year");

                    b.ToTable("academic_year", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admin");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_username");

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.AppNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("text")
                        .HasColumnName("attachment_path");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("RecipientLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_label");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_name");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.BackupAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("BackupFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backup_file_name");

                    b.Property<int?>("BackupId")
                        .HasColumnType("integer")
                        .HasColumnName("backup_id");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<int?>("PerformedById")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_id");

                    b.Property<string>("PerformedByName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("performed_by_name");

                    b.HasKey("Id")
                        .HasName("pk_backup_audit_logs");

                    b.ToTable("backup_audit_logs", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Campus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_campus");

                    b.ToTable("campus", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.DailyEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attendance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attendance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Evaluation")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("evaluation");

                    b.Property<string>("Homework")
                        .HasColumnType("text")
                        .HasColumnName("homework");

                    b.Property<string>("NewMemorization")
                        .HasColumnType("text")
                        .HasColumnName("new_memorization");

                    b.Property<string>("ReviewQuantity")
                        .HasColumnType("text")
                        .HasColumnName("review_quantity");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<string>("TeacherNote")
                        .HasColumnType("text")
                        .HasColumnName("teacher_note");

                    b.HasKey("Id")
                        .HasName("pk_daily_evaluation");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_daily_evaluation_student_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_daily_evaluation_teacher_id");

                    b.ToTable("daily_evaluation", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.DatabaseBackup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackupType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backup_type");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_name");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("directory");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<DateTime?>("RestoreDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("restore_date");

                    b.Property<string>("RestoreStatus")
                        .HasColumnType("text")
                        .HasColumnName("restore_status");

                    b.Property<int?>("RestoredBy")
                        .HasColumnType("integer")
                        .HasColumnName("restored_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_database_backups");

                    b.ToTable("database_backups", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.DatabaseBackupSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackupDirectory")
                        .HasColumnType("text")
                        .HasColumnName("backup_directory");

                    b.Property<string>("BackupTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backup_time");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<int>("MaxBackupsToKeep")
                        .HasColumnType("integer")
                        .HasColumnName("max_backups_to_keep");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_database_backup_settings");

                    b.ToTable("database_backup_settings", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("integer")
                        .HasColumnName("campus_id");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date")
                        .HasColumnName("exam_date");

                    b.Property<int>("ExamPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_plan_id");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exam_type");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_slot");

                    b.HasKey("Id")
                        .HasName("pk_exam");

                    b.HasIndex("CampusId")
                        .HasDatabaseName("ix_exam_campus_id");

                    b.HasIndex("ExamPlanId")
                        .HasDatabaseName("ix_exam_exam_plan_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_exam_group_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_exam_room_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_exam_teacher_id");

                    b.ToTable("exam", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.ExamPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer")
                        .HasColumnName("semester_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_exam_plan");

                    b.HasIndex("AcademicYearId")
                        .HasDatabaseName("ix_exam_plan_academic_year_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_exam_plan_created_by");

                    b.HasIndex("SemesterId")
                        .HasDatabaseName("ix_exam_plan_semester_id");

                    b.ToTable("exam_plan", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.ExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ContinuousEvaluation")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("continuous_evaluation");

                    b.Property<decimal?>("ExamGrade")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("exam_grade");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_id");

                    b.Property<decimal?>("FinalGrade")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("final_grade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_exam_result");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_exam_result_exam_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_exam_result_student_id");

                    b.ToTable("exam_result", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsFemale")
                        .HasColumnType("boolean")
                        .HasColumnName("is_female");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_group");

                    b.HasIndex("AcademicYearId")
                        .HasDatabaseName("ix_group_academic_year_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_group_teacher_id");

                    b.ToTable("group", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Homework", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_homework");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_homework_student_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_homework_teacher_id");

                    b.ToTable("homework", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.NotificationReceiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_full_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("pk_notification_receiver");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("ix_notification_receiver_notification_id");

                    b.ToTable("notification_receiver", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_parent");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_parent_username");

                    b.ToTable("parent", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_token_token");

                    b.ToTable("password_reset_token", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.RequiredDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_required_document");

                    b.ToTable("required_document", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.RevokedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jwt_id");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_revoked_token");

                    b.HasIndex("JwtId")
                        .IsUnique()
                        .HasDatabaseName("ix_revoked_token_jwt_id");

                    b.ToTable("revoked_token", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("integer")
                        .HasColumnName("campus_id");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_room");

                    b.HasIndex("CampusId")
                        .HasDatabaseName("ix_room_campus_id");

                    b.ToTable("room", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_semester");

                    b.HasIndex("AcademicYearId")
                        .HasDatabaseName("ix_semester_academic_year_id");

                    b.ToTable("semester", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsFemale")
                        .HasColumnType("boolean")
                        .HasColumnName("is_female");

                    b.Property<string>("OldMemorization")
                        .HasColumnType("text")
                        .HasColumnName("old_memorization");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("student_number");

                    b.Property<string>("StudentPhone")
                        .HasColumnType("text")
                        .HasColumnName("student_phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_student");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_student_group_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_student_parent_id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_student_serial_number");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_student_username");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.StudentDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_submitted");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("RequiredDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("required_document_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_student_document");

                    b.HasIndex("RequiredDocumentId")
                        .HasDatabaseName("ix_student_document_required_document_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_student_document_student_id");

                    b.ToTable("student_document", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.StudySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year_id");

                    b.Property<int>("CampusId")
                        .HasColumnType("integer")
                        .HasColumnName("campus_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_slot");

                    b.Property<string>("Weekday")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("weekday");

                    b.HasKey("Id")
                        .HasName("pk_study_schedule");

                    b.HasIndex("AcademicYearId")
                        .HasDatabaseName("ix_study_schedule_academic_year_id");

                    b.HasIndex("CampusId")
                        .HasDatabaseName("ix_study_schedule_campus_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_study_schedule_group_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_study_schedule_room_id");

                    b.ToTable("study_schedule", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFemale")
                        .HasColumnType("boolean")
                        .HasColumnName("is_female");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("RegistrationNumber")
                        .HasColumnType("integer")
                        .HasColumnName("registration_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_teacher");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_teacher_username");

                    b.ToTable("teacher", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.TeacherAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<string>("Justification")
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("pk_teacher_attendance");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_teacher_attendance_group_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_teacher_attendance_teacher_id");

                    b.ToTable("teacher_attendance", (string)null);
                });

            modelBuilder.Entity("QuranSchool.Api.Models.DailyEvaluation", b =>
                {
                    b.HasOne("QuranSchool.Api.Models.Student", "Student")
                        .WithMany("DailyEvaluations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_evaluation_student_student_id");

                    b.HasOne("QuranSchool.Api.Models.Teacher", "Teacher")
                        .WithMany("DailyEvaluations")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_evaluation_teacher_teacher_id");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Exam", b =>
                {
                    b.HasOne("QuranSchool.Api.Models.Campus", "Campus")
                        .WithMany("Exams")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_campus_campus_id");

                    b.HasOne("QuranSchool.Api.Models.ExamPlan", "ExamPlan")
                        .WithMany("Exams")
                        .HasForeignKey("ExamPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_exam_plan_exam_plan_id");

                    b.HasOne("QuranSchool.Api.Models.Group", "Group")
                        .WithMany("Exams")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_group_group_id");

                    b.HasOne("QuranSchool.Api.Models.Room", "Room")
                        .WithMany("Exams")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_room_room_id");

                    b.HasOne("QuranSchool.Api.Models.Teacher", "Teacher")
                        .WithMany("Exams")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_teacher_teacher_id");

                    b.Navigation("Campus");

                    b.Navigation("ExamPlan");

                    b.Navigation("Group");

                    b.Navigation("Room");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.ExamPlan", b =>
                {
                    b.HasOne("QuranSchool.Api.Models.AcademicYear", "AcademicYear")
                        .WithMany("ExamPlans")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_plan_academic_year_academic_year_id");

                    b.HasOne("QuranSchool.Api.Models.Admin", "Creator")
                        .WithMany("ExamPlans")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_plan_admin_created_by");

                    b.HasOne("QuranSchool.Api.Models.Semester", "Semester")
                        .WithMany("ExamPlans")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_plan_semester_semester_id");

                    b.Navigation("AcademicYear");

                    b.Navigation("Creator");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.ExamResult", b =>
                {
                    b.HasOne("QuranSchool.Api.Models.Exam", "Exam")
                        .WithMany("Results")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_result_exam_exam_id");

                    b.HasOne("QuranSchool.Api.Models.Student", "Student")
                        .WithMany("ExamResults")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_result_student_student_id");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Group", b =>
                {
                    b.HasOne("QuranSchool.Api.Models.AcademicYear", "AcademicYear")
                        .WithMany("Groups")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_academic_year_academic_year_id");

                    b.HasOne("QuranSchool.Api.Models.Teacher", "Teacher")
                        .WithMany("Groups")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_group_teacher_teacher_id");

                    b.Navigation("AcademicYear");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Homework", b =>
                {
                    b.HasOne("QuranSchool.Api.Models.Student", "Student")
                        .WithMany("Homeworks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_homework_student_student_id");

                    b.HasOne("QuranSchool.Api.Models.Teacher", "Teacher")
                        .WithMany("Homeworks")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_homework_teacher_teacher_id");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.NotificationReceiver", b =>
                {
                    b.HasOne("QuranSchool.Api.Models.AppNotification", "Notification")
                        .WithMany("Receivers")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_receiver_notification_notification_id");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Room", b =>
                {
                    b.HasOne("QuranSchool.Api.Models.Campus", "Campus")
                        .WithMany("Rooms")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_campus_campus_id");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Semester", b =>
                {
                    b.HasOne("QuranSchool.Api.Models.AcademicYear", "AcademicYear")
                        .WithMany("Semesters")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_semester_academic_year_academic_year_id");

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Student", b =>
                {
                    b.HasOne("QuranSchool.Api.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_student_group_group_id");

                    b.HasOne("QuranSchool.Api.Models.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_student_parent_parent_id");

                    b.Navigation("Group");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.StudentDocument", b =>
                {
                    b.HasOne("QuranSchool.Api.Models.RequiredDocument", "RequiredDocument")
                        .WithMany("StudentDocuments")
                        .HasForeignKey("RequiredDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_document_required_document_required_document_id");

                    b.HasOne("QuranSchool.Api.Models.Student", "Student")
                        .WithMany("StudentDocuments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_document_student_student_id");

                    b.Navigation("RequiredDocument");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.StudySchedule", b =>
                {
                    b.HasOne("QuranSchool.Api.Models.AcademicYear", "AcademicYear")
                        .WithMany("StudySchedules")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_study_schedule_academic_year_academic_year_id");

                    b.HasOne("QuranSchool.Api.Models.Campus", "Campus")
                        .WithMany("StudySchedules")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_study_schedule_campus_campus_id");

                    b.HasOne("QuranSchool.Api.Models.Group", "Group")
                        .WithMany("StudySchedules")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_study_schedule_group_group_id");

                    b.HasOne("QuranSchool.Api.Models.Room", "Room")
                        .WithMany("StudySchedules")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_study_schedule_room_room_id");

                    b.Navigation("AcademicYear");

                    b.Navigation("Campus");

                    b.Navigation("Group");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.TeacherAttendance", b =>
                {
                    b.HasOne("QuranSchool.Api.Models.Group", "Group")
                        .WithMany("TeacherAttendances")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_attendance_group_group_id");

                    b.HasOne("QuranSchool.Api.Models.Teacher", "Teacher")
                        .WithMany("TeacherAttendances")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_attendance_teacher_teacher_id");

                    b.Navigation("Group");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.AcademicYear", b =>
                {
                    b.Navigation("ExamPlans");

                    b.Navigation("Groups");

                    b.Navigation("Semesters");

                    b.Navigation("StudySchedules");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Admin", b =>
                {
                    b.Navigation("ExamPlans");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.AppNotification", b =>
                {
                    b.Navigation("Receivers");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Campus", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Rooms");

                    b.Navigation("StudySchedules");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Exam", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.ExamPlan", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Group", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Students");

                    b.Navigation("StudySchedules");

                    b.Navigation("TeacherAttendances");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Parent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.RequiredDocument", b =>
                {
                    b.Navigation("StudentDocuments");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Room", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("StudySchedules");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Semester", b =>
                {
                    b.Navigation("ExamPlans");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Student", b =>
                {
                    b.Navigation("DailyEvaluations");

                    b.Navigation("ExamResults");

                    b.Navigation("Homeworks");

                    b.Navigation("StudentDocuments");
                });

            modelBuilder.Entity("QuranSchool.Api.Models.Teacher", b =>
                {
                    b.Navigation("DailyEvaluations");

                    b.Navigation("Exams");

                    b.Navigation("Groups");

                    b.Navigation("Homeworks");

                    b.Navigation("TeacherAttendances");
                });
#pragma warning restore 612, 618
        }
    }
}
